language: node_js
node_js:
  - 0.10

before_install:
  - npm install -g codeclimate-test-reporter

notifications:
  email: true

cache:
  directories:
    - node_modules

after_script:
  - node Build/PublishCodeCoverage.js